alias l='lsd -h --color=always --group-directories-first'
alias ll='lsd -lh --color=always --group-directories-first'
alias la='lsd -Ah --color=always --group-directories-first'
alias lal='lsd -Alh --color=always --group-directories-first'
alias vim="vim -u $XDG_CONFIG_HOME/dotfiles/.vimrc -i $XDG_CONFIG_HOME/dotfiles/.viminfo"
alias mgrep='grep --color=always -C1'
alias less='less -R'
alias mpacman='pacman --color=always'
alias aocc='source /opt/AOCC/setenv_AOCC.sh'
alias nctl='networkctl'
alias tmuxlist='tmux list-sessions'
alias tmuxkill='tmux kill-session -a'
alias tmux='tmux -2'
export AURWEB='https://aur.archlinux.org'
export ARCHWEB='https://gitlab.archlinux.org/archlinux/packaging/packages'

